version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/node:7.10
      - image: circleci/postgres:9.6.2

    working_directory: ~/where-is-grey

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/where-is-grey/vendor/bundle

      - run: cp dummy-env .env
      # We need psql 9.6 for db:structure:load
      - run: |
          wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update -qq
          sudo apt-get install -y postgresql-client-9.6
      - run: bundle exec rake db:create
      - run: bundle exec rake db:structure:load
      - run:
          name: run tests
          command: bundle exec rspec spec
